# Generated by Django 5.1.5 on 2025-02-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_mngt', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
