# Generated by Django 5.1.5 on 2025-02-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_mngt', '0004_account_dob_alter_account_email_alter_account_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
