# Generated by Django 5.1.5 on 2025-02-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_mngt', '0009_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
